  
### Action Items


- Gantt view (feature branch Gantt-view;web component, tests, docs)
  - [x] Add a gantt view that shows tasks on a timeline based on their due dates and durations, allowing for easy visualization of task dependencies and scheduling.
  - [x] Add a view selector to toggle to the gantt view.
  - [x] support dragging an arrow from one task to another to indicate a dependency between the two tasks.
  - [ ] support highlighting tasks that are on the critical path in red.
  - [x] support dragging tasks to change their due dates and durations, with the gantt chart updating accordingly.
  - [x] support zooming in and out of the timeline for better visibility of tasks with different durations.
  - [x] visualize uncertainty with a boxplot whisker
  - [x] milestones are tasks with zero duration, and are visualized as diamonds on the gantt chart.
  - [x] shrink the note to a single line hide the badges and show just the title.
  - [x] add handles in the left center and right for
  - [x] drag the bars left/right using a handle in the the left tip - thus changing the start date of the task
  - [x] extend the duration by dragging a handle in the right tip
  - [x] drag an arrow to link a task that depends on the current task's completion - by dragging a small handle from the center
  - [ ] support filtering tasks by project in the gantt view. 


- BugsFixes (on bugfix branch Bug-fixes)
  - [x] The testing dashboard filters don't respond to clicks.
  - [ ] The task composer input should repond to enter as a submit action.
- Storage and Data
